config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :answers

  resources :exercises

  devise_for :usuarios

  root 'welcome#index'

  get '/exercises/' => 'exercises#index'

  resources :answers

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/ejercicio.rb
class Ejercicio < ActiveRecord::Base
	has_many :answers
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
end

app/models/respuesta.rb
class Respuesta < ActiveRecord::Base
	belongs_to :ejercicio
	belongs_to :usuario 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    # @answers = Answer.all
    # respond_with(@answers)
  end

  def show
    # respond_with(@answer)
  end

  def new
    # @answer = Answer.new
    # respond_with(@answer)
  end

  def edit
  end

  def create
    # @answer = Answer.new(answer_params)
    # @answer.save
    # respond_with(@answer)
  end

  def update
    # @answer.update(answer_params)
    # respond_with(@answer)
  end

  def destroy
    # @answer.destroy
    # respond_with(@answer)
  end

  private
    def set_answer
      # @answer = Answer.find(params[:id])
    end

    def answer_params
      # params.require(:answer).permit(:body, :word_count, :exercise, :user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ejercicios_controller.rb
class EjerciciosController < ApplicationController

	def index
    @ejercicios = Ejercicio.all
  end
 
  def show
    @ejercicio = Ejercicio.find(params[:id])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @exercises = Exercise.all
  end
 
  def show
    @exercise = Exercise.find(params[:id])
  end

  def new
    # @exercise = Exercise.new
    # respond_with(@exercise)
  end

  def edit
  end

  def create
    # @exercise = Exercise.new(exercise_params)
    # @exercise.save
    # respond_with(@exercise)
  end

  def update
    # @exercise.update(exercise_params)
    # respond_with(@exercise)
  end

  def destroy
    # @exercise.destroy
    # respond_with(@exercise)
  end

  private
    def set_exercise
      # @exercise = Exercise.find(params[:id])
    end

    def exercise_params
      # params.require(:exercise).permit(:instructions, :title)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
  end
end

app/controllers/respuestas_controller.rb
class RespuestasController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ejercicios_helper.rb
module EjerciciosHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :word_count %><br>
    <%= f.number_field :word_count %>
  </div>
  <div class="field">
    <%= f.label :exercise %><br>
    <%= f.text_field :exercise %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Word count</th>
      <th>Exercise</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.body %></td>
        <td><%= answer.word_count %></td>
        <td><%= answer.exercise %></td>
        <td><%= answer.user %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
 <script type=""text/javascript"">
  var cnt;
  function wordcount(count) {
    var words = count.split(/\s/);
    cnt = words.length;
    var ele = document.getElementById('w_count');
    ele.value = cnt;
  }
  document.write("<input type=text id=w_count size=4 readonly>");
</script>

<%= form_for Answer.new do |f| %>
  <%= f.text_area :body,  onkeyup: "wordcount(this.value)", style: "width:550px; height:200px;" %>
 
  <%= f.submit "Guardar" %>
<% end %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>Word count:</strong>
  <%= @answer.word_count %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @answer.exercise %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/ejercicios/index.html.erb
<!-- Fixed navbar -->


<div id="ejercicios-titulo">
<div class="container">
	<div class="row">
		<div class="col-lg-6">
		<h1>Ejercicios de escritura</h4>
		</div>
	</div>
</div>
</div>


<div class="container ejercicios">
	<div class="row">
		<div class="col-lg-12 ">
			<% Ejercicio.all.each do |e| %>
			<h2 style="color:#FB4655;"><%= e.titulo %></h2>
		</div><!-- col-lg-6 -->
		<div class="col-lg-12 ">
			<p><%= e.instrucciones %></p>
			<%= link_to "Escribe", "/respuestas/new", class: "btn btn-warning btn-lg" %>
			<% end %>
		</div>
	</div><!-- row -->
</div><!-- container -->
	



<div id="frase">
	<div class="container">
		<div class="row centered">
			<div class="col-lg-8 col-lg-offset-2">
				<h4>THIS WILL BE AN INSPIRATIONAL QUOTE.</h4>
				<p>Esta es una frase muy inspiradora que va a cambiarte la vida. Va a cambiar cada vez que refrescas la página. </p>
			</div>
		</div><!-- row -->
	</div><!-- container -->
</div> 

app/views/ejercicios/show.html.erb
<h1>Escritor.Co</h1>
<p>EJERCICIOS</p>

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<div id="ejercicios-titulo">
<div class="container">
  <div class="row">
    <div class="col-lg-6">
    <h1>Ejercicios de escritura</h4>
    </div>
  </div>
</div>
</div>


<div class="container ejercicios">
  <div class="row">
    <div class="col-lg-12 ">
      <% Exercise.all.each do |e| %>
      <h2 style="color:#FB4655;"><%= e.title %></h2>
    </div><!-- col-lg-6 -->
    <div class="col-lg-12 ">
      <p><%= e.instructions %></p>
      <%= link_to "Escribe", "/answers/new", class: "btn btn-warning btn-lg" %>
      <% end %>
    </div>
  </div><!-- row -->
</div><!-- container -->
  



<div id="frase">
  <div class="container">
    <div class="row centered">
      <div class="col-lg-8 col-lg-offset-2">
        <h4>THIS WILL BE AN INSPIRATIONAL QUOTE.</h4>
        <p>Esta es una frase muy inspiradora que va a cambiarte la vida. Va a cambiar cada vez que refrescas la página. </p>
      </div>
    </div><!-- row -->
  </div><!-- container -->
</div> 

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instructions:</strong>
  <%= @exercise.instructions %>
</p>

<p>
  <strong>Title:</strong>
  <%= @exercise.title %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EscritorApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img class="logo" src="/assets/banner-transparente.png" alt="Escritor.Co"></a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
        </ul>
      </div>
        <li><a href="/exercises">Ejercicios</a></li>


        <% if current_usuario %>
          <li><a href="/profile">Tu perfil</a></li>
          <li><a href="/users/sign_out" data-method="delete">Logout</a></li>
        <% else %>
          <li><a href="/users/sign_in">Sign In</a></li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse
  </div>
</div> -->


<!-- FOOTER -->
<!-- <div id="footer">
<div class="container">
	<div class="row">
		<div class="col-lg-6">
			<p>¡Contáctanos!</p>
			<p><small>Hecho con <i class="fa fa-heart"></i> en<br>
				Sacatepéquez, Guatemala<br>
				</small>
		  </p>
		  <p><small>Copyright © Escritor.Co 2015<br>
		    <br></small>
		  </p>
		</div>
	</div>
</div> --><!-- container -->
<!-- </div> --><!-- Footer -->

</body>
</html>

app/views/respuestas/new.html.erb
 <script type=""text/javascript"">
  var cnt;
  function wordcount(count) {
    var words = count.split(/\s/);
    cnt = words.length;
    var ele = document.getElementById('w_count');
    ele.value = cnt;
  }
  document.write("<input type=text id=w_count size=4 readonly>");
</script>

<%= form_for Respuesta.new, url: "/respuestas" do |f| %>
  <%= f.text_area :body,  onkeyup: "wordcount(this.value)", style: "width:550px; height:200px;" %>
 
  <%= f.submit "Guardar" %>
<% end %>

app/views/welcome/index.html.erb
<h1>Escritor.Co</h1>
<p>Esta es la aplicación de Escritor.Co</p>